version: '3.8'

services:
  mongodb-dev:
    image: mongo:6.0
    container_name: mongodb-dev
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: devuser
      MONGO_INITDB_ROOT_PASSWORD: devpass
    volumes:
      - mongodb_dev_data:/data/db
    networks:
      - fastapi_mongo_net
    restart: unless-stopped  # 👈 Optional: ensures the container restarts unless stopped manually

volumes:
  mongodb_dev_data:

networks:
  fastapi_mongo_net:
    external: true  # 👈 Let Docker know you're using a pre-created network
